import { Settings, Shift, Task, TaskLog, ThemePreset } from "@/lib/types";
import { getDateOffsetISO } from "@/lib/date";

export const THEME_PRESETS: Record<string, ThemePreset> = {
  milkBlue: {
    key: "milkBlue",
    name: "奶蓝",
    bg: "from-sky-100 via-cyan-50 to-blue-100",
    card: "bg-white/78",
    soft: "bg-sky-100 text-sky-700",
    accent: "bg-sky-500",
    accentText: "text-sky-700",
    ring: "ring-sky-200",
    button: "bg-sky-500 hover:bg-sky-600 text-white",
    iconHex: "#0ea5e9",
  },
  sakura: {
    key: "sakura",
    name: "樱花粉",
    bg: "from-pink-100 via-rose-50 to-fuchsia-100",
    card: "bg-white/78",
    soft: "bg-pink-100 text-pink-700",
    accent: "bg-pink-500",
    accentText: "text-pink-700",
    ring: "ring-pink-200",
    button: "bg-pink-500 hover:bg-pink-600 text-white",
    iconHex: "#ec4899",
  },
  cream: {
    key: "cream",
    name: "奶油黄",
    bg: "from-amber-100 via-yellow-50 to-orange-100",
    card: "bg-white/78",
    soft: "bg-amber-100 text-amber-700",
    accent: "bg-amber-500",
    accentText: "text-amber-700",
    ring: "ring-amber-200",
    button: "bg-amber-500 hover:bg-amber-600 text-white",
    iconHex: "#f59e0b",
  },
  sage: {
    key: "sage",
    name: "鼠尾草绿",
    bg: "from-emerald-100 via-green-50 to-lime-100",
    card: "bg-white/78",
    soft: "bg-emerald-100 text-emerald-700",
    accent: "bg-emerald-500",
    accentText: "text-emerald-700",
    ring: "ring-emerald-200",
    button: "bg-emerald-500 hover:bg-emerald-600 text-white",
    iconHex: "#10b981",
  },
  lavender: {
    key: "lavender",
    name: "薰衣草紫",
    bg: "from-violet-100 via-purple-50 to-fuchsia-100",
    card: "bg-white/78",
    soft: "bg-violet-100 text-violet-700",
    accent: "bg-violet-500",
    accentText: "text-violet-700",
    ring: "ring-violet-200",
    button: "bg-violet-500 hover:bg-violet-600 text-white",
    iconHex: "#8b5cf6",
  },
};

export const DEFAULT_SETTINGS: Settings = {
  theme: "milkBlue",
  darkMode: false,
  wallpaper: "",
  defaultBreakMinutes: 30,
  defaultHourlyRate: 17.4,
  weekStartsOnMonday: true,
  currency: "CAD",
  language: "zh-CN",
  paidBreak: false,
  overtimeThresholdHours: 8,
  overtimeMultiplier: 1.5,
  weekendMultiplier: 1.15,
  holidayMultiplier: 1.5,
  taxRate: 0.12,
  showNetPay: false,
  locationRates: {
    "Vancouver Branch": 17.4,
    "Richmond Branch": 18.2,
  },
  reminders: {
    beforeWork: true,
    afterWork: true,
    missingRecord: true,
    weeklySummary: true,
  },
};

export const SAMPLE_SHIFTS: Shift[] = [
  {
    id: crypto.randomUUID(),
    date: getDateOffsetISO(0),
    locationName: "Vancouver Branch",
    roleName: "Intern",
    startTime: "14:00",
    endTime: "19:00",
    breakMinutes: 30,
    isDayOff: false,
    isBreakPaid: false,
    baseHourlyRate: 17.4,
    bonusAmount: 0,
    tipsAmount: 0,
    deductionAmount: 0,
    note: "完成日报",
    tags: ["实习"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    date: getDateOffsetISO(1),
    locationName: "Vancouver Branch",
    roleName: "Intern",
    startTime: "12:00",
    endTime: "17:00",
    breakMinutes: 30,
    isDayOff: false,
    isBreakPaid: false,
    baseHourlyRate: 17.4,
    bonusAmount: 0,
    tipsAmount: 0,
    deductionAmount: 0,
    note: "",
    tags: ["轮班"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    date: getDateOffsetISO(3),
    locationName: "Richmond Branch",
    roleName: "Support",
    startTime: "12:00",
    endTime: "18:30",
    breakMinutes: 30,
    isDayOff: false,
    isBreakPaid: false,
    baseHourlyRate: 18.2,
    bonusAmount: 8,
    tipsAmount: 0,
    deductionAmount: 0,
    note: "帮忙补位",
    tags: ["轮班"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_TASKS: Task[] = [
  {
    id: crypto.randomUUID(),
    title: "打卡上班",
    category: "work",
    color: "sky",
    icon: "✨",
    priority: "high",
    repeatRule: "daily",
    reminderEnabled: true,
    streakCount: 2,
    note: "",
  },
  {
    id: crypto.randomUUID(),
    title: "完成日报",
    category: "work",
    color: "pink",
    icon: "📝",
    priority: "medium",
    repeatRule: "daily",
    reminderEnabled: true,
    streakCount: 4,
    note: "",
  },
  {
    id: crypto.randomUUID(),
    title: "面试准备 30 分钟",
    category: "study",
    color: "violet",
    icon: "📚",
    priority: "medium",
    repeatRule: "daily",
    reminderEnabled: false,
    streakCount: 3,
    note: "",
  },
  {
    id: crypto.randomUUID(),
    title: "喝水提醒",
    category: "health",
    color: "emerald",
    icon: "💧",
    priority: "low",
    repeatRule: "daily",
    reminderEnabled: true,
    streakCount: 5,
    note: "",
  },
];

export const SAMPLE_TASK_LOGS: TaskLog[] = SAMPLE_TASKS.map((task, index) => ({
  id: crypto.randomUUID(),
  taskId: task.id,
  date: getDateOffsetISO(0),
  completed: index < 2,
  completedAt: index < 2 ? new Date().toISOString() : null,
}));
